### ISSUE TITLE
MultiThreadedApplicationAdapter.java  compile error

### ISSUE THREAD

**Issue by folousiot** [Red5/red5-server#273] opened 2019-06-21 07:55 UTC
yesterday i download the latest red5-server project, and also download the red5-parent-master，red5-io-master，red5-server-common-master，red5-service-master，but comile have some errors, as folows:
Description	Resource	Path	Location	Type
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 962	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 979	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 997	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1015	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1028	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1041	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1054	Java Problem
JDKSchedulingService cannot be resolved to a type	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 1066	Java Problem
The import org.red5.server.scheduling cannot be resolved	MultiThreadedApplicationAdapter.java	/red5-server-master/src/main/java/org/red5/server/adapter	line 71	Java Problem

**Comment by folousiot** [comment] 2019-06-21 08:00
two errors:
**1、JDKSchedulingService cannot be resolved to a type**
/red5-server-master/src/main/java/org/red5/server/adapter/MultiThreadedApplicationAdapter.java
line 962,line 979,line 997,line 1015,line 1028,line 1041,line 1054,line 1066
**2、The import org.red5.server.scheduling cannot be resolved**
/red5-server-master/src/main/java/org/red5/server/adapter/MultiThreadedApplicationAdapter.java
line 71

**Comment by mondain** [comment] 2019-07-25 14:50
Dupe of #272

**Closed by mondain** 2019-07-25 14:50 UTC
